### PR TITLE
some potential improvements

### PR DESCRIPTION
**Pull request by John-Colvin**
Hi, saw your article and saw the code, but was disappointed to see `D` not performing as well as I expected. However, with some small modifications, I can easily get it down to 0.13s per iteration on my macbook pro using `ldc2`.

The rearrangement commit just makes it easier to test an optimised build (`dub` doesn't have a unittest-release setting, see https://github.com/D-Programming-Language/dub/issues/747), as well as being a bit neater.

Changes that are for style:
- use slicing instead of modifying `.length`
- `for` -> `foreach`

Changes for performance:
- use an `appender` instead of raw appending.
- disable GC collections, those millions of small allocations from all the stuff like `s ~= "e"` are a nightmare for the GC. Note we are still collecting the memory in the end (and including that time in the benchmark).
- not benchmarked, but writing to a file by calling `append` for each element is very slow, so I use `std.stdio.File.write` with `std.algorithm.joiner` instead.

I think there is still a lot more performance to be got. A few suggestions:
- This is all ASCII, yes? functions like replaceInPlace can't assume this for strings, you may get better performance using `std.utf.byCodeUnit` or casting to `ubyte[]` (remember `string` is `immutable(char)[]`, so the correct cast would be to `immutable(ubyte)[]`)
- Using a mutable string buffer instead of immutable would allow you to do a lot more in-place and lot less `~=`, which is likely a big performance cost. If you like using appending in the body of the code for clarity, you could make a custom string type that manually maintains the buffer and overloads `opOpAssign(string op : "~")` and/or try using `std.array.appender` with its `reserve` and `strinkTo` methods to achieve the same thing.

### CODE REVIEW

**Comment by John-Colvin** [comment]
P.S. if you somehow don't use the builtin `~=` inside `stem`, you will likely not be using the GC at all and will be able to dispense with all the `disable`/`enable`/`collect` stuff.

P.P.S. `replaceInPlace` isn't actually in-place in the way you would expect, because unicode is a pain.

**Comment by John-Colvin** [comment]
There is an integer overflow bug in the benchmark printout in https://github.com/John-Colvin/PorterStemmer/commit/a5c9ad0a6053e590672333915cd3e07f087bf4ff, the true value was about 0.13s per iteration, have edited the original comment to reflect that.

Added a few more optimisations, now down to 0.06s per iteration.

**Comment by rharriso** [comment]
@John-Colvin I'd like my library to support unicode. a text base I work with a lot is a historical text so has French, Greek, and other characters. Although the stemmer won't do anything for them. I make a habit to try to support them anyway.

There could be an opportunity for an ascii only version though.

**Comment by rharriso** [comment]
I like the other changes you've made, moving the benchmark file, using foreach, compile time tuple arrays. I'd like to merge those in without the ascii assumptions.

However, I will be trying to bench against the C implementation, so an ascii version might be beneficial, I'm not sure what the best way would be, static ifs around every assignment could get nasty.

Can we make some substitution method that checks the type? It looks like [we wouldn't be able to](https://dlang.org/spec/function.html#inline-functions) force in-lining.

**Comment by rharriso** [comment]
@John-Colvin I just ran your benchmarks on my machine and got 0.04 seconds per cycle with both ldc and gdc, very cool.

I'm going to try doing a version that supports utf8 as well. I'll open a pull when I think I have something

**Pull request merged**
